// <auto-generated />
namespace BookingSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class citydistrctaded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(citydistrctaded));
        
        string IMigrationMetadata.Id
        {
            get { return "201909032043277_city-distrct aded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
